[platformio]
src_dir = src

[env]
platform = https://github.com/SeeedJP/platform-nordicnrf52.git#8f55ff26c0822ffcbff978be1fddfb8c88c57577
platform_packages =
    framework-arduinoadafruitnrf52 @ https://github.com/SeeedJP/Adafruit_nRF52_Arduino.git#514f28ee405952ecc58558b5e0608a2b63d9901a
framework = arduino
board = seeed_wio_bg770a
board_upload.maximum_size = 397312
monitor_speed = 115200
build_flags =
    -DBOARD_VERSION_1_0
    -DCFG_LOGGER=0
lib_archive = no
lib_extra_dirs = ../../lib
lib_deps =
    seeedjp/WioCellular@0.3.15
    bblanchon/ArduinoJson@7.0.4

[env:ota_v1]
build_flags =
    ${env.build_flags}
    -DAPP_VERSION=1

[env:ota_v2]
build_flags =
    ${env.build_flags}
    -DAPP_VERSION=2
