[platformio]
default_envs = bootstrap, blinky_v2, lte_bootstrap
src_dir = apps

[env]
platform = https://github.com/SeeedJP/platform-nordicnrf52.git#8f55ff26c0822ffcbff978be1fddfb8c88c57577
platform_packages =
    framework-arduinoadafruitnrf52 @ https://github.com/SeeedJP/Adafruit_nRF52_Arduino.git#514f28ee405952ecc58558b5e0608a2b63d9901a
framework = arduino
board = seeed_wio_bg770a
board_upload.maximum_size = 397312
monitor_speed = 115200
build_flags =
    -DBOARD_VERSION_1_0
    -DCFG_LOGGER=3
lib_archive = no

[env:bootstrap]
build_src_filter =
    +<bootstrap/>
    -<blinky_v2/>
    -<lte_bootstrap/>

[env:blinky_v2]
build_src_filter =
    -<bootstrap/>
    +<blinky_v2/>
    -<lte_bootstrap/>

[env:lte_bootstrap]
build_flags =
    -DBOARD_VERSION_1_0
    -DCFG_LOGGER=0
build_src_filter =
    -<bootstrap/>
    -<blinky_v2/>
    +<lte_bootstrap/>
lib_deps =
    seeedjp/WioCellular@0.3.15
    bblanchon/ArduinoJson@7.0.4

[env:lte_bootstrap_apply]
extends = env:lte_bootstrap
build_flags =
    ${env:lte_bootstrap.build_flags}
    -DWIO_OTA_ENABLED=1
    -DWIO_OTA_AUTO_APPLY=1

[env:lte_target_v3]
extends = env:lte_bootstrap
build_flags =
    ${env:lte_bootstrap.build_flags}
    -DWIO_OTA_ENABLED=1
    -DWIO_OTA_CURRENT_VERSION=3

[env:lte_target_v3_apply]
extends = env:lte_bootstrap
build_flags =
    ${env:lte_bootstrap.build_flags}
    -DWIO_OTA_ENABLED=1
    -DWIO_OTA_AUTO_APPLY=1
    -DWIO_OTA_CURRENT_VERSION=3

[env:lte_target_v4]
extends = env:lte_bootstrap
build_flags =
    ${env:lte_bootstrap.build_flags}
    -DWIO_OTA_ENABLED=1
    -DWIO_OTA_AUTO_APPLY=1
    -DWIO_OTA_CURRENT_VERSION=4
